# -*- coding: utf-8 -*-
"""Global Mobile Prices Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ObcoAfbAzl0kKYj0XgNRaMhE_6AxoBcA

# Global Mobile Prices

This dataset contains information about mobile phones from different brands, including their specifications and prices across the world.  
The goal is to explore price trends and patterns based on features like RAM, Storage, Battery, Brand, and Release Year.

# Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Ignore all warnings"""

import warnings
warnings.filterwarnings('ignore')

"""# Load Dataset"""

df = pd.read_csv("/content/Global_Mobile_Prices_2025_Extended.csv")
df.head()

"""# Basic Info & EDA

#  Dataset info
"""

df.info()

"""# Check missing values"""

df.isnull().sum()

"""# Summary statistics"""

df.describe()

"""# Fill numeric missing values"""

numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

"""# Fill categorical missing values"""

categorical_cols = df.select_dtypes(include='object').columns
df[categorical_cols] = df[categorical_cols].fillna(df[categorical_cols].mode().iloc[0])

"""# Simple Visualizations

# Price Distribution
"""

plt.figure(figsize=(10,5))
sns.histplot(df['price_usd'], bins=50, kde=True, color='skyblue')
plt.title("Price Distribution")
plt.show()

"""# RAM vs Price (scatter plot)"""

plt.figure(figsize=(10,5))
sns.scatterplot(x='ram_gb', y='price_usd', data=df, hue='brand', palette='tab10')
plt.title("RAM vs Price by Brand")
plt.show()

